# Generated by Django 6.0.6 on 2026-07-12 18:36

import api.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('available', 'Available'), ('pending', 'Pending Payment'), ('booked', 'Booked')], default='available', max_length=10)),
                ('hold_expires_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['room', 'bed_number'],
            },
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('boys', 'Boys Hostel'), ('girls', 'Girls Hostel')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.ImageField(blank=True, null=True, upload_to=api.models.hostel_image_path)),
                ('warden_name', models.CharField(blank=True, max_length=150)),
                ('warden_phone', models.CharField(blank=True, max_length=20)),
                ('location_notes', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_reference', models.CharField(default=api.models.generate_booking_reference, editable=False, max_length=30, unique=True)),
                ('full_name', models.CharField(help_text='Full name as per KCSE certificate', max_length=200)),
                ('registration_number', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(help_text='Phone number that will be charged via M-Pesa', max_length=20)),
                ('is_minor', models.BooleanField(default=False)),
                ('id_number', models.CharField(blank=True, help_text='National ID number, required if 18 or older', max_length=20)),
                ('birth_certificate_number', models.CharField(blank=True, help_text='Birth certificate number, required if under 18', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending_payment', max_length=20)),
                ('receipt_number', models.CharField(blank=True, max_length=40)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to=api.models.qr_code_path)),
                ('receipt_email_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('bed', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='booking', to='api.bed')),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='api.hostel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MpesaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('merchant_request_id', models.CharField(blank=True, max_length=100)),
                ('checkout_request_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled by user')], default='pending', max_length=10)),
                ('result_code', models.CharField(blank=True, max_length=10)),
                ('result_desc', models.CharField(blank=True, max_length=255)),
                ('mpesa_receipt_number', models.CharField(blank=True, max_length=50)),
                ('transaction_date', models.CharField(blank=True, max_length=20)),
                ('raw_callback', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_transaction', to='api.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20)),
                ('floor', models.CharField(blank=True, max_length=20)),
                ('capacity', models.PositiveSmallIntegerField(default=4, help_text='Number of beds in this room')),
                ('is_active', models.BooleanField(default=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='api.hostel')),
            ],
            options={
                'ordering': ['hostel', 'room_number'],
                'unique_together': {('hostel', 'room_number')},
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='api.room'),
        ),
        migrations.AddField(
            model_name='bed',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='api.room'),
        ),
        migrations.AlterUniqueTogether(
            name='bed',
            unique_together={('room', 'bed_number')},
        ),
    ]
